name: Coverage

on: [push]

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: pnpm
              uses: ianwalter/pnpm-container@v1.1.0
              run: |
                  pnpm i 
                  pnpm run coverage
